services:
  web:
    build:
      context: .
      args:
        ODOO_VERSION: ${ODOO_VERSION}
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./third_party_addons:/mnt/third-party-addons
      - ./third_party_addons/web:/mnt/third-party-addons/web
      - odoo-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      # Важно для дебага: заставляем Odoo работать в один поток
      - ODOO_WORKERS=0
    command: odoo --http-interface=0.0.0.0 
      --db_host=db
      --db_user=${DB_USER}
      --db_password=${DB_PASSWORD}
      --addons-path=/mnt/extra-addons,/mnt/third-party-addons,/mnt/third-party-addons/web
    tty: true
  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  odoo-db-data: