services:
  web:
    build:
      context: .
      args:
        ODOO_VERSION: ${ODOO_VERSION}
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      # Важно для дебага: заставляем Odoo работать в один поток
      - ODOO_WORKERS=0

  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  odoo-db-data: